package ru.lionzxy.tplauncher.ui

object Strings {
    const val serverAddress = "games.glitchless.ru"
    const val login = "Логин"
    const val password = "Пароль"
    const val server = "Сервер"
    const val launchSettings = "Настройки запуска"
    const val registerOnSite = "Регистрация на сайте"
    const val enterGame = "Войти в игру"
    const val loggedIn = "Вход осуществлен"
    const val enterLoginAndPassword = "Введите логин и пароль"
    const val goodGame = "Приятной игры"
    const val loadingGame = "Загружаем игру..."
    const val launchingMinecraft = "Запускаем Minecraft..."
    const val enterValidEmail = "Введите валидную почту"
    const val passwordCannotBeEmpty = "Пароль не может быть пустым"
    const val checkInternetConnection = "Проверьте подключение к интернету"
    const val internalError = "Внутреняя ошибка, мы уже исправляем это"
    const val memorySize = "Объем памяти"
    const val javaParams = "Параметры java"
    const val prefix = "Prefix"
    const val javaPath = "Путь до Java"
    const val debugMode = "Дебаг-режим"
    const val autoJoinServer = "Авто-заход на сервер"
    const val showLogs = "Показать логи"
    const val uiScale = "Масштаб интерфейса"
    const val logsTitle = "Логи"
    const val scrollToEnd = "В конец"
    const val copyLogs = "Копировать"
    const val saveLogs = "Сохранить"
    const val saveLogDialogTitle = "Сохранить лог"
    const val goToGameDirectory = "Перейти в директорию игры"
    const val logout = "Выйти из аккаунта"
    const val deleteGameAndReset = "Удалить игру и сбросить настройки лаунчера"
    const val back = "Вернуться"
    const val apply = "Применить"

    fun authByEmail(email: String) = "Авторизация по email $email..."
    fun clearBackup(size: String) = "Очистить папку с бекапом ($size)"
}
